### ISSUE TITLE
TypeError: Highway.forward: return type `<class 'torch.Tensor'>` is not a `<class 'NoneType'>`.

### ISSUE THREAD

**Issue by zyx214** [JackHCC/Chinese-Keyphrase-Extraction#1]
![image](https://user-images.githubusercontent.com/76771357/190543978-7bddaeb9-5d6b-4898-b0e3-d064f7be9dab.png)
请问这怎么解决呢，用的是sifrank方法

**Comment by JackHCC** [comment]
数据注意按照Readme说明格式构造，参数设置好，环境配置好
