### ISSUE TITLE
我是按照您的代码和环境跑的，为什么我plus等于True和Flase的结果都是一样的呢？

### ISSUE THREAD

**Issue by 19961115yuyang** [JackHCC/Chinese-Keyphrase-Extraction#2]
def SIF_rank(text, plus=True, lambda_=0.8, elmo_layers_weight=[0.0, 1.0, 0.0]):
这里的plus我也试着改了，结果还是没有变化

**Comment by JackHCC** [comment]
可能是数据太少了看不出区别
